name: Build & test project

on: [push]
  pull request:
    types: [opened, reopened]
    types: [review_requested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Build project with maven
        working-directory: .
        run: |
          mvn test
